- Name: "广州群"
  PageCount: 1
- Name: "宝妈群"
  PageCount: 1
- Name: "闲置群"
  PageCount: 1
- Name: "二手群"
  PageCount: 1
- Name: "微商群"
  PageCount: 1
- Name: "创业群"
  PageCount: 1
- Name: "交友群"
  PageCount: 1
- Name: "交流群"
  PageCount: 1
- Name: "互砍群"
  PageCount: 1
- Name: "砍价群"
  PageCount: 1
- Name: "互助群"
  PageCount: 2
- Name: "外卖群"
  PageCount: 1
- Name: "优惠券群"
  PageCount: 1
- Name: "线报群"
  PageCount: 1
- Name: "拼多多群"
  PageCount: 5
- Name: "拼多多微信群"
  PageCount: 3
- Name: "拼多多砍价"
  PageCount: 3
- Name: "王者荣耀微信群"
  PageCount: 1