; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "»ðä½"
!define PRODUCT_VERSION "#replace_version#"
!define PRODUCT_PUBLISHER "Ò»µ¶"
!define PRODUCT_WEB_SITE "https://github.com/laosanyuan/HuoHuan"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\HuoHuan.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "HuoHuan\Resources\HuoHuan.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "..\docs\HuohuanAuthorizationDocument.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\HuoHuan.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\»ðä½"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "HuoHuan\bin\publish\AngleSharp.dll"
  File "HuoHuan\bin\publish\CalcBinding.dll"
  File "HuoHuan\bin\publish\CommunityToolkit.Mvvm.dll"
  File "HuoHuan\bin\publish\Dapper.Contrib.dll"
  File "HuoHuan\bin\publish\Dapper.dll"
  File "HuoHuan\bin\publish\DynamicExpresso.Core.dll"
  File "HuoHuan\bin\publish\EntityFramework.dll"
  File "HuoHuan\bin\publish\EntityFramework.SqlServer.dll"
  File "HuoHuan\bin\publish\HuoHuan.DataBase.dll"
  File "HuoHuan\bin\publish\HuoHuan.DataBase.pdb"
  File "HuoHuan\bin\publish\HuoHuan.deps.json"
  File "HuoHuan\bin\publish\HuoHuan.dll"
  File "HuoHuan\bin\publish\HuoHuan.exe"
  CreateDirectory "$SMPROGRAMS\»ðä½"
  CreateShortCut "$SMPROGRAMS\»ðä½\»ðä½.lnk" "$INSTDIR\HuoHuan.exe"
  CreateShortCut "$DESKTOP\»ðä½.lnk" "$INSTDIR\HuoHuan.exe"
  File "HuoHuan\bin\publish\HuoHuan.pdb"
  File "HuoHuan\bin\publish\HuoHuan.Plugin.Contracs.dll"
  File "HuoHuan\bin\publish\HuoHuan.Plugin.Contracs.pdb"
  File "HuoHuan\bin\publish\HuoHuan.Plugin.Plugins.dll"
  File "HuoHuan\bin\publish\HuoHuan.Plugin.Plugins.pdb"
  File "HuoHuan\bin\publish\HuoHuan.runtimeconfig.json"
  File "HuoHuan\bin\publish\HuoHuan.Utils.dll"
  File "HuoHuan\bin\publish\HuoHuan.Utils.pdb"
  SetOutPath "$INSTDIR\inference\ch_PP-OCRv3_det_infer"
  File "HuoHuan\bin\publish\inference\ch_PP-OCRv3_det_infer\._inference.pdiparams"
  File "HuoHuan\bin\publish\inference\ch_PP-OCRv3_det_infer\._inference.pdiparams.info"
  File "HuoHuan\bin\publish\inference\ch_PP-OCRv3_det_infer\._inference.pdmodel"
  File "HuoHuan\bin\publish\inference\ch_PP-OCRv3_det_infer\inference.pdiparams"
  File "HuoHuan\bin\publish\inference\ch_PP-OCRv3_det_infer\inference.pdiparams.info"
  File "HuoHuan\bin\publish\inference\ch_PP-OCRv3_det_infer\inference.pdmodel"
  SetOutPath "$INSTDIR\inference\ch_PP-OCRv3_rec_infer"
  File "HuoHuan\bin\publish\inference\ch_PP-OCRv3_rec_infer\inference.pdiparams"
  File "HuoHuan\bin\publish\inference\ch_PP-OCRv3_rec_infer\inference.pdiparams.info"
  File "HuoHuan\bin\publish\inference\ch_PP-OCRv3_rec_infer\inference.pdmodel"
  SetOutPath "$INSTDIR\inference\ch_ppocr_mobile_v2.0_cls_infer"
  File "HuoHuan\bin\publish\inference\ch_ppocr_mobile_v2.0_cls_infer\inference.pdiparams"
  File "HuoHuan\bin\publish\inference\ch_ppocr_mobile_v2.0_cls_infer\inference.pdiparams.info"
  File "HuoHuan\bin\publish\inference\ch_ppocr_mobile_v2.0_cls_infer\inference.pdmodel"
  SetOutPath "$INSTDIR\inference"
  File "HuoHuan\bin\publish\inference\ppocr_keys.txt"
  SetOutPath "$INSTDIR"
  File "HuoHuan\bin\publish\libiomp5md.dll"
  File "HuoHuan\bin\publish\Microsoft.Extensions.FileProviders.Abstractions.dll"
  File "HuoHuan\bin\publish\Microsoft.Extensions.FileProviders.Embedded.dll"
  File "HuoHuan\bin\publish\Microsoft.Extensions.Primitives.dll"
  File "HuoHuan\bin\publish\mkldnn.dll"
  File "HuoHuan\bin\publish\mklml.dll"
  File "HuoHuan\bin\publish\Newtonsoft.Json.dll"
  File "HuoHuan\bin\publish\Ninject.dll"
  File "HuoHuan\bin\publish\OpenCvSharp.dll"
  File "HuoHuan\bin\publish\OpenCvSharp.Extensions.dll"
  File "HuoHuan\bin\publish\opencv_world411.dll"
  File "HuoHuan\bin\publish\PaddleOCR.dll"
  File "HuoHuan\bin\publish\PaddleOCRSharp.dll"
  File "HuoHuan\bin\publish\paddle_inference.dll"
  SetOutPath "$INSTDIR\Resources\Fonts"
  File "HuoHuan\bin\publish\Resources\Fonts\iconfont.ttf"
  File "HuoHuan\bin\publish\Resources\Fonts\jiangxizhuokai.ttf"
  File "HuoHuan\bin\publish\Resources\Fonts\siyuansong.ttf"
  File "HuoHuan\bin\publish\Resources\Fonts\xiaoweilogo.ttf"
  SetOutPath "$INSTDIR\runtimes\linux-x64\native"
  File "HuoHuan\bin\publish\runtimes\linux-x64\native\SQLite.Interop.dll"
  SetOutPath "$INSTDIR\runtimes\osx-x64\native"
  File "HuoHuan\bin\publish\runtimes\osx-x64\native\SQLite.Interop.dll"
  SetOutPath "$INSTDIR\runtimes\unix\lib\netcoreapp2.1"
  File "HuoHuan\bin\publish\runtimes\unix\lib\netcoreapp2.1\System.Data.SqlClient.dll"
  SetOutPath "$INSTDIR\runtimes\win\lib\netcoreapp2.1"
  File "HuoHuan\bin\publish\runtimes\win\lib\netcoreapp2.1\System.Data.SqlClient.dll"
  SetOutPath "$INSTDIR\runtimes\win-arm64\native"
  File "HuoHuan\bin\publish\runtimes\win-arm64\native\sni.dll"
  SetOutPath "$INSTDIR\runtimes\win-x64\native"
  File "HuoHuan\bin\publish\runtimes\win-x64\native\OpenCvSharpExtern.dll"
  File "HuoHuan\bin\publish\runtimes\win-x64\native\opencv_videoio_ffmpeg460_64.dll"
  File "HuoHuan\bin\publish\runtimes\win-x64\native\sni.dll"
  File "HuoHuan\bin\publish\runtimes\win-x64\native\SQLite.Interop.dll"
  SetOutPath "$INSTDIR\runtimes\win-x86\native"
  File "HuoHuan\bin\publish\runtimes\win-x86\native\OpenCvSharpExtern.dll"
  File "HuoHuan\bin\publish\runtimes\win-x86\native\opencv_videoio_ffmpeg460.dll"
  File "HuoHuan\bin\publish\runtimes\win-x86\native\sni.dll"
  File "HuoHuan\bin\publish\runtimes\win-x86\native\SQLite.Interop.dll"
  SetOutPath "$INSTDIR"
  File "HuoHuan\bin\publish\System.Data.SqlClient.dll"
  File "HuoHuan\bin\publish\System.Data.SQLite.dll"
  File "HuoHuan\bin\publish\System.Data.SQLite.EF6.dll"
  File "HuoHuan\bin\publish\YamlDotNet.dll"
  File "HuoHuan\bin\publish\zxing.dll"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\»ðä½\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\»ðä½\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\HuoHuan.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\HuoHuan.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) ÒÑ³É¹¦µØ´ÓÄãµÄ¼ÆËã»úÒÆ³ý¡£"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "ÄãÈ·ÊµÒªÍêÈ«ÒÆ³ý $(^Name) £¬Æä¼°ËùÓÐµÄ×é¼þ£¿" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\zxing.dll"
  Delete "$INSTDIR\YamlDotNet.dll"
  Delete "$INSTDIR\System.Data.SQLite.EF6.dll"
  Delete "$INSTDIR\System.Data.SQLite.dll"
  Delete "$INSTDIR\System.Data.SqlClient.dll"
  Delete "$INSTDIR\runtimes\win-x86\native\SQLite.Interop.dll"
  Delete "$INSTDIR\runtimes\win-x86\native\sni.dll"
  Delete "$INSTDIR\runtimes\win-x86\native\opencv_videoio_ffmpeg460.dll"
  Delete "$INSTDIR\runtimes\win-x86\native\OpenCvSharpExtern.dll"
  Delete "$INSTDIR\runtimes\win-x64\native\SQLite.Interop.dll"
  Delete "$INSTDIR\runtimes\win-x64\native\sni.dll"
  Delete "$INSTDIR\runtimes\win-x64\native\opencv_videoio_ffmpeg460_64.dll"
  Delete "$INSTDIR\runtimes\win-x64\native\OpenCvSharpExtern.dll"
  Delete "$INSTDIR\runtimes\win-arm64\native\sni.dll"
  Delete "$INSTDIR\runtimes\win\lib\netcoreapp2.1\System.Data.SqlClient.dll"
  Delete "$INSTDIR\runtimes\unix\lib\netcoreapp2.1\System.Data.SqlClient.dll"
  Delete "$INSTDIR\runtimes\osx-x64\native\SQLite.Interop.dll"
  Delete "$INSTDIR\runtimes\linux-x64\native\SQLite.Interop.dll"
  Delete "$INSTDIR\Resources\Fonts\xiaoweilogo.ttf"
  Delete "$INSTDIR\Resources\Fonts\siyuansong.ttf"
  Delete "$INSTDIR\Resources\Fonts\jiangxizhuokai.ttf"
  Delete "$INSTDIR\Resources\Fonts\iconfont.ttf"
  Delete "$INSTDIR\paddle_inference.dll"
  Delete "$INSTDIR\PaddleOCRSharp.dll"
  Delete "$INSTDIR\PaddleOCR.dll"
  Delete "$INSTDIR\opencv_world411.dll"
  Delete "$INSTDIR\OpenCvSharp.Extensions.dll"
  Delete "$INSTDIR\OpenCvSharp.dll"
  Delete "$INSTDIR\Ninject.dll"
  Delete "$INSTDIR\Newtonsoft.Json.dll"
  Delete "$INSTDIR\mklml.dll"
  Delete "$INSTDIR\mkldnn.dll"
  Delete "$INSTDIR\Microsoft.Extensions.Primitives.dll"
  Delete "$INSTDIR\Microsoft.Extensions.FileProviders.Embedded.dll"
  Delete "$INSTDIR\Microsoft.Extensions.FileProviders.Abstractions.dll"
  Delete "$INSTDIR\libiomp5md.dll"
  Delete "$INSTDIR\inference\ppocr_keys.txt"
  Delete "$INSTDIR\inference\ch_ppocr_mobile_v2.0_cls_infer\inference.pdmodel"
  Delete "$INSTDIR\inference\ch_ppocr_mobile_v2.0_cls_infer\inference.pdiparams.info"
  Delete "$INSTDIR\inference\ch_ppocr_mobile_v2.0_cls_infer\inference.pdiparams"
  Delete "$INSTDIR\inference\ch_PP-OCRv3_rec_infer\inference.pdmodel"
  Delete "$INSTDIR\inference\ch_PP-OCRv3_rec_infer\inference.pdiparams.info"
  Delete "$INSTDIR\inference\ch_PP-OCRv3_rec_infer\inference.pdiparams"
  Delete "$INSTDIR\inference\ch_PP-OCRv3_det_infer\inference.pdmodel"
  Delete "$INSTDIR\inference\ch_PP-OCRv3_det_infer\inference.pdiparams.info"
  Delete "$INSTDIR\inference\ch_PP-OCRv3_det_infer\inference.pdiparams"
  Delete "$INSTDIR\inference\ch_PP-OCRv3_det_infer\._inference.pdmodel"
  Delete "$INSTDIR\inference\ch_PP-OCRv3_det_infer\._inference.pdiparams.info"
  Delete "$INSTDIR\inference\ch_PP-OCRv3_det_infer\._inference.pdiparams"
  Delete "$INSTDIR\HuoHuan.Utils.pdb"
  Delete "$INSTDIR\HuoHuan.Utils.dll"
  Delete "$INSTDIR\HuoHuan.runtimeconfig.json"
  Delete "$INSTDIR\HuoHuan.Plugin.Plugins.pdb"
  Delete "$INSTDIR\HuoHuan.Plugin.Plugins.dll"
  Delete "$INSTDIR\HuoHuan.Plugin.Contracs.pdb"
  Delete "$INSTDIR\HuoHuan.Plugin.Contracs.dll"
  Delete "$INSTDIR\HuoHuan.pdb"
  Delete "$INSTDIR\HuoHuan.exe"
  Delete "$INSTDIR\HuoHuan.dll"
  Delete "$INSTDIR\HuoHuan.deps.json"
  Delete "$INSTDIR\HuoHuan.DataBase.pdb"
  Delete "$INSTDIR\HuoHuan.DataBase.dll"
  Delete "$INSTDIR\EntityFramework.SqlServer.dll"
  Delete "$INSTDIR\EntityFramework.dll"
  Delete "$INSTDIR\DynamicExpresso.Core.dll"
  Delete "$INSTDIR\Dapper.dll"
  Delete "$INSTDIR\Dapper.Contrib.dll"
  Delete "$INSTDIR\CommunityToolkit.Mvvm.dll"
  Delete "$INSTDIR\CalcBinding.dll"
  Delete "$INSTDIR\AngleSharp.dll"

  Delete "$SMPROGRAMS\»ðä½\Uninstall.lnk"
  Delete "$SMPROGRAMS\»ðä½\Website.lnk"
  Delete "$DESKTOP\»ðä½.lnk"
  Delete "$SMPROGRAMS\»ðä½\»ðä½.lnk"

  RMDir "$SMPROGRAMS\»ðä½"
  RMDir "$INSTDIR\runtimes\win-x86\native"
  RMDir "$INSTDIR\runtimes\win-x64\native"
  RMDir "$INSTDIR\runtimes\win-arm64\native"
  RMDir "$INSTDIR\runtimes\win\lib\netcoreapp2.1"
  RMDir "$INSTDIR\runtimes\unix\lib\netcoreapp2.1"
  RMDir "$INSTDIR\runtimes\osx-x64\native"
  RMDir "$INSTDIR\runtimes\linux-x64\native"
  RMDir "$INSTDIR\Resources\Fonts"
  RMDir "$INSTDIR\inference\ch_PP-OCRv3_rec_infer"
  RMDir "$INSTDIR\inference\ch_PP-OCRv3_det_infer"
  RMDir "$INSTDIR\inference\ch_ppocr_mobile_v2.0_cls_infer"
  RMDir "$INSTDIR\inference"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd