name: Huohuan - CI

on:
  push:
    branches: [ master, feature, dev]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 安装.Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: 安装Nuget
      uses: nuget/setup-nuget@v1
    - run: nuget restore src\HuoHuan.sln
    - name: 编译
      run: dotnet build src\HuoHuan.sln --no-restore -c ${{ matrix.configuration }}
    - name: 单元测试
      run: dotnet test src\HuoHuan.sln -c $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
